steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    id: "Install dependencies"
  
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
    id: "Build static files"

  - name: "gcr.io/cloud-builders/gsutil"
    args: ["-m", "rsync", "-r", "./build", "gs://deeli-landing-page"]
    id: "Copy static files to GCS"

timeout: 300s