import React, { useState, useEffect } from "react";
import { 
  Box, 
  Container, 
  Typography, 
  useMediaQuery, 
  CircularProgress,
  AppBar,
  Toolbar,
  Button
} from "@mui/material";
import { useTheme } from "@mui/material/styles";
import { ArrowLeft } from "phosphor-react";
import ReactMarkdown from "react-markdown";
import Logo from "../assets/logo.svg";

const TERMS_CONTENT = `**Deeli AI, Inc. Terms of Service**

**Last Updated: June 15, 2025**

These Terms of Service (the “**_Terms_**”) are a binding contract between you or the entity you represent (“**_Customer_**”, “**_you_**”, or “**_your_**”) and Deeli AI, Inc. (“**_Deeli_**”, “**_we_**”, or “**_us_**”).  These Terms govern your access to and use of Deeli’s website available at [www.deeli.ai](http://www.deeli.ai) (the “**_Website_**”), the artificial-intelligence powered platform detailed on the Website, specifically Deeli Intelligence (the “**_Platform_**”), and any content, tools, features and functionality offered on or through the Website or the Platform (collectively, the “**_Services_**”). By accessing or using the Services, you agree to these Terms. 

If you do not understand or agree to these Terms, please do not use the Services. For purposes of these Terms, “you” and “your” means you as the user of the Services. If you use the Services on behalf of a company or other entity then “you” includes you and that entity, and you represent and warrant that (a) you are an authorized representative of the entity with the authority to bind the entity to these Terms, and (b) you agree to these Terms on the entity’s behalf.

1. **Definitions**. The following terms shall be defined as follows:

   1. “**_Authorized User(s)_**” means Customer’s employees, consultants, contractors, and agents (i) who are authorized by Customer to access and use the Services under the rights granted to Customer pursuant to this Terms and (ii) for whom access to the Services has been purchased hereunder. 

   2. “**_Confidential Information_**” means information about either party’s business affairs, products, confidential intellectual property, trade secrets, third-party confidential information, and other sensitive or proprietary information, in any form, which information is marked confidential, restricted, proprietary, or with a similar designation, or which a reasonable person would determine, by virtue of the nature of the information or the method under which it was disclosed or other facts and circumstances, should be treated as confidential.  Confidential Information does not include information that, at the time of disclosure, is: (a) in the public domain; (b) known to the receiving party; (c) rightfully obtained by the receiving party on a non-confidential basis from a third party; or (d) independently developed by the receiving party.

   3. “**_Customer Data_**” means Input and any other content, materials or data supplied by Customer to Deeli, either directly through the Services or indirectly through the integration with a Third-Party Product, for processing on Customer’s behalf. Customer Data does not include Aggregated Statistics.

   4. “**_Deeli Property_**” means the Services, the Documentation, and all content and other materials and software supplied by Deeli in connection with, or used by Deeli in providing, any Services. For the avoidance of doubt, Deeli Property includes Aggregated Statistics, but does not include Customer Data. Deeli Property includes all modifications, enhancements, refinements, adaptations, customizations, improvements, and derivative works of the Services.

   5. “**_Documentation_**” means any technical guides, reference materials, tutorials, FAQs, and instructional videos relating to the Services provided by Deeli to you electronically and relating to the Services available on the Website.  

   6. “**_Input_**” means information, data, materials, text, or other content that is input, prompted, uploaded, or submitted by or on behalf of Customer or any other Authorized User through the Services.

   7. “**_Intellectual Property Rights_**” means all patent rights, copyright rights, mask work rights, moral rights, rights of publicity, trademark, trade dress and service mark rights, goodwill, trade secret rights and other intellectual property rights as may now exist or hereafter come into existence, and all applications therefore and registrations, renewals and extensions thereof, under the laws of any state, country, territory or other jurisdiction.

   8. “**_Output_**” means information, data, materials, text, images, or other content generated by the Services based on an Input. 

   9. “**_Personal Information_**” means information relating to an identified or identifiable natural person that relates to, describes, is reasonably capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular natural person. 

   10. “**_Third-Party Products_**” means any products, content, services, information, websites, or other materials that are owned by third parties and are incorporated into or accessible through the Services.

2. **Access and Use of the Services**. 

   1. Access to the Services. Subject to and conditioned on your compliance with these Terms, Deeli hereby grants you a non-exclusive, non-sublicensable, non-transferable, revokable right to access and use the Services and Documentation during the Term, solely for your business purposes by Authorized Users under the terms and conditions herein.  

   2. Use Restrictions. You shall not use the Services for any purposes beyond the scope of the access granted in these Terms. You shall not at any time, directly or indirectly, and shall not permit any Authorized Users to: (i) copy, modify, or create derivative works of the Services or Documentation, in whole or in part; (ii) rent, lease, lend, sell, license, sublicense, assign, distribute, publish, transfer, or otherwise make available the Services or Documentation; (iii) reverse engineer, disassemble, decompile, decode, or duplicate the Services, reproduce training data, engage in model extraction, or otherwise attempt to derive or gain access to any source code, algorithm, model, model weights and parameters, or other underlying AI technology or component of the Services, in whole or in part; (iv) access or use the Services or any Output to develop, train, or improve a competing or similar product or service; (v) use web scraping, web harvesting, web data extraction or any other method to extract data from the Services or any Output; (vi) remove any proprietary notices from the Services or Documentation; (vii) use the Services to create or generate Output, or use Output in a manner, that you know or should know infringes, misappropriates, or otherwise violates any Intellectual Property Right or other right of any person, or that violates any applicable law, regulation, or rule; or (viii) submit, enter, post, or otherwise transmit or process any Personal Information through the Services.

   3. Aggregated Statistics. Notwithstanding anything to the contrary in these Terms, Deeli may collect and compile data and information related to Customer’s use of the Services to be used by Deeli in an aggregated and anonymized manner, including to compile statistical and performance information related to the provision and operation of the Services (the “**_Aggregated Statistics_**”). As between Deeli and Customer, all right, title, and interest in Aggregated Statistics, and all Intellectual Property Rights therein, belong to and are retained solely by Deeli. You agree that Deeli may use and make publicly available Aggregated Statistics to the extent and in the manner permitted under applicable law, provided that such Aggregated Statistics do not identify Customer or Customer’s Confidential Information.

   4. Reservation of Rights. Deeli reserves all rights not expressly granted to Customer in these Terms. Except for the limited rights and licenses expressly granted under these Terms, nothing in these Terms grants, by implication, waiver, estoppel, or otherwise, to Customer or any third party, any Intellectual Property Rights or other right, title, or interest in or to the Deeli Property.

   5. Suspension. Notwithstanding anything to the contrary in these Terms, Deeli may temporarily suspend or permanently terminate any Customer’s and any other Authorized User’s access to any portion or all of the Services, for any reason or no reason, with or without notice, including but not limited to if: (i) Deeli reasonably determines that (A) there is a threat or attack on any of the Deeli Property; (B) Customer’s or any other Authorized User’s use of the Deeli Property disrupts or poses a security risk to the Deeli Property, to Deeli, or to any other customer or vendor of Deeli; (C) Customer or any other Authorized User is using the Deeli Property for fraudulent or illegal activities; (D) subject to applicable law, Customer has ceased to continue its business in the ordinary course, made an assignment for the benefit of creditors or similar disposition of its assets, or become the subject of any bankruptcy, reorganization, liquidation, dissolution, or similar proceeding; (E) Deeli’s provision of the Services to Customer or any other Authorized User is prohibited by applicable law; or (F) Customer is using the Services in material violation of Section 2(b) (Use Restrictions) herein; (ii) any vendor of Deeli has suspended or terminated Deeli’s access to or use of any third-party services or products required to enable Customer to access and use the Services; or (iii) in accordance with Section 4(a) (Fees and Payment).  Deeli will have no liability for any damages, liabilities, losses (including any loss of data or profits), or any other consequences that Customer or any other Authorized User may incur as a result of such suspension or termination.

   6. Changes to the Services. We may, without prior notice, (i) change the Services; (ii) stop providing the Services or features of the Services, to you or to users generally; or (iii) create usage limits for the Services. You agree that Deeli shall not be liable for any loss or damage caused, directly or indirectly, by any such change or discontinuance.

3. **Customer Responsibilities**. 

   1. Acceptable Use. The Services may not be used for unlawful, fraudulent, offensive, or obscene activity. You further agree to comply with all terms and conditions of these Terms, all applicable laws, rules, and regulations, and all guidelines, standards, requirements, and policies that may be posted on the Website from time to time. 

   2. Account Use. Customer must establish an account to access the Services and certain functionality we may develop from time to time (“**_Account_**”).  You are responsible for all use of the Services and Documentation and other activities that occur under your Account, including resulting from access provided by you, directly or indirectly, whether that access or use is permitted by or in violation of these Terms. Without limiting the generality of the foregoing, you are responsible for all acts and omissions of Authorized Users, and any act or omission by an Authorized User that would constitute a breach of these Terms if taken by you will be deemed a breach of these Terms by you. You shall use reasonable efforts to make all Authorized Users aware of these Terms to the extent applicable to such Authorized User’s use of the Services and shall cause Authorized Users to comply with such applicable provisions.  

   3. Passwords and Access Credentials. When creating your Account, you must provide accurate and complete information, and you must keep this information up to date. You are solely responsible for activity that occurs on your Account and are responsible for keeping your passwords and access credentials associated with the Services confidential. You shall not sell or transfer them to any other person or entity. You shall promptly notify us about any unauthorized access to your passwords or access credentials.

   4. Use of Output. You are solely responsible for (i) evaluating (including by human review) Output for accuracy, completeness, and other factors relevant to your use before using, distributing, or relying on the Output, and (ii) your decisions, actions, and omissions in reliance or based on the Output.

   5. Third-Party Products.  The Services may permit access to Third-Party Products. For purposes of these Terms, such Third-Party Products are subject to their own terms and conditions presented to you for acceptance within the Services by website link or otherwise. If you do not agree to abide by the applicable terms for any such Third-Party Products, then you should not install, access, or use such Third-Party Products. Deeli does not endorse or assume any responsibility for any such Third-Party Products. If you access a Third-Party Product from the Services or share your Customer Data on or through any third-party website or service, you do so at your own risk, and you understand that these Terms and Deeli’s Privacy Policy do not apply to your use of such sites. 

4. **Fees and Payment**.

   1. Fees.  ****Certain aspects of the Services may be provided for a fee or other charge. If you elect to use paid aspects of the Services, Customer shall pay Deeli the fees as described in any applicable ordering documentation without offset or deduction. Customer shall make all payments thereunder on or before the applicable due date and in the currency specified in the ordering documentation. If Customer fails to make any payment when due, without limiting Deeli’s other rights and remedies: (i) Deeli may charge interest on the past due amount at the rate of 1.5% per month calculated daily and compounded monthly or, if lower, the highest rate permitted under applicable law; (ii) Customer shall reimburse Deeli for all reasonable costs incurred by Deeli in collecting any late payments or interest, including attorneys’ fees, court costs, and collection agency fees; and (iii) if the failure continues for thirty (30) days or more, Deeli may suspend, under Section 2(e) (Suspension), Customer’s and all other Authorized Users’ access to any portion or all of the Services until such amounts are paid in full.  Deeli may add new services for additional fees and charges or amend fees and charges for existing services, at any time in its sole discretion.

   2. Payment Methods; Taxes. All information that you provide in connection with a purchase or other monetary transaction relating to the Services must be accurate, complete, and current. You agree to pay all charges incurred by users of your credit card, debit card, or other payment method used in connection with a purchase or other monetary transaction relating to the Services at the prices in effect when such charges are incurred. All fees and other amounts payable by Customer under these Terms are exclusive of taxes and similar assessments. Customer is responsible for all sales, use, and excise taxes, and any other similar taxes, duties, tariffs, and charges of any kind imposed by any federal, state, or local governmental or regulatory authority on any amounts payable by Customer hereunder, other than any taxes imposed on Deeli’s income.

   3. No Refunds. You may cancel your Account at any time; however, there are no refunds for cancellation. If Deeli suspends or terminates your Account, you agree that you shall receive no refund or exchange for any unused time on a subscription, any license, or subscription fees for any portion of the Services, any content or data associated with your Account, or for anything else. 

   4. Trial Periods. We may offer free trial periods for particular Services.  We may automatically bill your payment method on the later of the day your free trial ends or on the day you start a paid subscription, and on each recurring billing date thereafter unless you notify us that you want to cancel your subscription. 

5. **Confidential Information**. 

From time to time during the Term, Deeli and Customer may disclose or make available to the other party Confidential Information. The receiving party shall not disclose the disclosing party’s Confidential Information to any person or entity, except to the receiving party’s employees, agents, or subcontractors who have a need to know the Confidential Information for the receiving party to exercise its rights or perform its obligations hereunder and who are required to protect the Confidential Information in a manner no less stringent than required under these Terms. Notwithstanding the foregoing, each party may disclose Confidential Information to the limited extent required (i) to comply with the order of a court or other governmental body, or as otherwise necessary to comply with applicable law, provided that the party making the disclosure pursuant to the order shall first have given written notice to the other party and made a reasonable effort to obtain a protective order; or (ii) to establish a party’s rights under these Terms, including to make required court filings. Each party’s obligations of non-disclosure regarding Confidential Information are effective as of the date the Confidential Information is first disclosed to the receiving party and will expire three years thereafter; provided, however, for any Confidential Information that constitutes a trade secret (as determined under applicable law), those obligations of non-disclosure will survive the termination or expiration of these Terms for as long as the Confidential Information remains subject to trade secret protection under applicable law.

6. **Privacy Policy**. 

In providing the Services, Deeli complies with its privacy policy provided separately to Customer (the “[**_Privacy Policy_**](http://url505.deeli.ai/ls/click?upn=u001.fNNn5nLKkLaamAIEZexaVFTEx37rSg4BSEnSSXlK11e3ZUhTTizfAdBuxLrqm4rt8CLXLBisD1bCXMTup1bfp3ZFLxfWRWr2KasBT85QTy7Xesw09HV0JCCAsWELyrUjysKvosPAYTr3Sm-2BBIDMwjuW0gfQ-2FA6QU3QrG42zrZS8-3DwonO_cIUsIvsqJNgUBXjA608pW-2BZq4XSWgRjd1J1ib-2BzJPID9dfirxwasQLcCND3WH8pYAbWwbC-2FlLNbYlk7BQ-2FqGoRI7lIMj2-2BnbfQBDJyGiQyFj2FkD7-2B-2BO5mjfAbf-2FQa-2BwJskwGgS4mjZZtk9XLJc274vBh2VhRgLNZ3NeFABs7xxr7J5vuo39C93PbgVdjH6xloHJ1pl9z-2BDulkl5Vb05rw-3D-3D)”). The Privacy Policy is subject to change as described therein. By accessing, using, and providing information to or through the Services, you acknowledge that you have reviewed and accepted our Privacy Policy, and you consent to all actions taken by us with respect to your information in compliance with the then-current version of our Privacy Policy.

7. **Term; Termination**.

   1. Term. The term of these Terms will commence upon the earlier of your acceptance of these Terms, any ordering documentation, or the date you first use the Services, and will remain in effect until terminated pursuant to this Section 7 (“**_Term_**”). If you purchase a subscription to the Services, the subscription term will be set forth in the ordering documentation and will automatically renew for successive periods unless either of us gives the other notice of its intent not to renew. That notice must be given at least thirty (30) days before the start of the next renewal period. 

   2. Termination. Either party may terminate this Agreement upon written notice (a) if the other party materially breaches this Agreement and does not cure the breach within thirty (30) days after receiving written notice of the breach or (b) if the other party ceases its business operations or becomes subject to insolvency proceedings. We may suspend your or any Authorized User’s access to the Services or terminate these Terms or any order documentation: (i) if required to do so by law; (ii) to prevent a security risk or other credible risk of harm or liability to us, the Services, or any third party; or (iii) for violations of the Sections 2(b) (Restrictions on Use) and 3(a) (Acceptable Use). 

   3. Effect of Termination. Upon expiration or termination of this Agreement, Customer shall immediately discontinue use of Deeli Property. Termination or expiration will not affect any rights or obligations, including the payment of amounts due, which have accrued under these Terms up to the date of termination or expiration. Upon any termination or expiration of this Agreement, the provisions that are intended by their nature to survive termination will survive and continue in full force and effect in accordance with their terms, including confidentiality obligations, limitations of liability, and disclaimers. 

   4. Survival. Sections 4 (Fees and Payment), 5 (Confidential Information), 8 (Intellectual Property), 10 (Indemnification), 11 (Limitation of Liability), and 13 (Miscellaneous) and any right, obligation, or required performance of the parties to these Terms which, by its express terms or nature and context is intended to survive the termination of these Terms, will survive.

8. **Intellectual Property**. 

   1. Deeli Property. Customer acknowledges that, as between Customer and Deeli, Deeli owns all rights, title, and interest, including all Intellectual Property Rights, in and to the Deeli Property and, for Third-Party Products, the applicable third-party providers own all right, title, and interest, including all Intellectual Property Rights, in and to the Third-Party Products. Deeli hereby grants you a non-exclusive, royalty-free, worldwide, revokable license during the Term to access and use the Deeli Property solely for your business operations by Authorized Users in accordance with the terms and conditions herein.  

   2. Customer Data.  As between Deeli and Customer, Customer owns all right, title, and interest, including all Intellectual Property Rights, in and to the Customer Data, except (i) as set out in Section 8(a) with respect to Deeli Property, (ii) with respect to Deeli Confidential Information, and (iii) with respect to Third-Party Products. By submitting, posting, displaying, providing, or otherwise making available any Customer Data on or through the Services, you expressly grant, and you represent and warrant that you have all rights necessary to grant, to Deeli a royalty-free, sublicensable, transferable, perpetual, irrevocable, non-exclusive, worldwide license to reproduce, distribute, and otherwise use and display the Customer Data and process the Customer Data to (i) provide the Services to Customer, and (ii) exercise our rights under these Terms, including the right to develop, train, improve, commercially offer, and create derivative works of the Services and new products and services. You further acknowledge that we may aggregate some or all of Customer Data and may share that aggregated information with third parties; provided, however, that such aggregated information will not identify you or any User individually. Additionally, for the Term, you grant Deeli a non-exclusive, irrevocable license to use Customer’s name, trademarks and logos to identify Customer as a user of the Services. Notwithstanding anything in these Terms to the contrary, unless prohibited by applicable law, we may delete Customer Data at any time if we determine that Customer Data violates these Terms or that the deletion is necessary to comply with applicable law. 

   3. Feedback.  You may choose to, or we may invite you to, submit Feedback. If you or any other Authorized User sends or transmits any communications or materials to us by mail, email, or otherwise, suggesting or recommending changes to the Services, including without limitation, new features or functionality relating thereto, or any comments, questions, suggestions, or the like (“**_Feedback_**”), we are free to use that Feedback. All Feedback is and will be treated as non-confidential. You hereby assign to us on your behalf, and shall cause your Authorized Users to assign to us, all right, title, and interest in, and we are free to use, without any attribution or compensation to you or any third party, any ideas, know-how, concepts, techniques, or other intellectual property rights contained in the Feedback, for any purpose whatsoever, although we are have no obligation to acknowledge receipt of or use any Feedback.

9. **Warranty Disclaimer**. 

THE SERVICES AND OUTPUT ARE PROVIDED “AS IS” AND ON AN “AS AVAILABLE” BASIS.  USE OF THE SERVICES IS AT YOUR OWN RISK.  DEELI SPECIFICALLY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE.  DEELI SPECIFICALLY DISCLAIMS ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT, AND ALL WARRANTIES ARISING FROM COURSE OF DEALING, USAGE, OR TRADE PRACTICE.  DEELI MAKES NO WARRANTY OF ANY KIND THAT THE SERVICES, OR ANY PRODUCTS OR RESULTS OF THE USE THEREOF, INCLUDING ANY OUTPUTS, WILL MEET YOUR OR ANY OTHER PERSON’S OR ENTITY’S REQUIREMENTS, OPERATE WITHOUT INTERRUPTION, ACHIEVE ANY INTENDED RESULT, BE COMPATIBLE OR WORK WITH ANY OF YOUR OR ANY THIRD PARTY’S SOFTWARE, SYSTEM, OR OTHER SERVICES, OR BE SECURE, ACCURATE, COMPLETE, FREE OF HARMFUL CODE, OR ERROR-FREE, OR THAT ANY ERRORS OR DEFECTS CAN OR WILL BE CORRECTED.  YOU ACKNOWLEDGE THAT, GIVEN THE NATURE OF THE SERVICES AND AI TECHNOLOGY, OUTPUT (I) MAY BE INACCURATE, (II) MAY BE THE SAME AS OR SIMILAR TO OUTPUT THE SERVICES GENERATE FOR OTHER CUSTOMERS, (III) MAY NOT QUALIFY FOR INTELLECTUAL PROPERTY PROTECTION, AND (IV) MAY BE SUBJECT TO THIRD PARTY TERMS.

10. **Indemnification**. 

    1. By Customer. You agree to defend, hold harmless, and indemnify us and our Affiliates, officers, directors, agents, and employees, from and against any third-party claims, including any liability or expense arising from any claims, losses, damages (actual and consequential, direct, indirect, and punitive), suits, judgments, litigation costs, and attorneys’ fees, of every kind and nature (collectively, “**Claims**”), arising from or in any way related to your or any of your Affiliates’ or Authorized Users’: (i) Customer’s use of the Services in violation of this Agreement; (ii) Customer Data; and/or (iii) Customer’s gross negligence or willful misconduct.

    2. By Us. We agree to defend, hold harmless, and indemnify you and your officers, directors, agents, and employees, from and against any Claims alleging the Services or Outputs generated by Customer in accordance with the terms of this Agreement infringe any third-party intellectual property right.  This excludes claims to the extent arising from: (a) combination of any Services or Outputs with any non-Deeli products, services, content, data or software; (b) Customer having insufficient rights in the relevant Input; (c) Customer’s use of the Output; (d) Third-Party Products; or (e) Customer’s gross negligence, willful misconduct, or breach of this Agreement. If we reasonably believe that all or any portion of the Services is likely to become the subject of any infringement claim, we may (x) procure, at its expense, the right for you to continue using the Services in accordance with this Agreement, (y) replace or modify the allegedly infringing Service so it is non-infringing, or (z), if (x) and (y) are not commercially practicable, terminate this Agreement. Customer shall promptly comply with all reasonable instructions we provide with respect to (x) and (y) above.

    3. Indemnification Procedures. If any third party makes a Claim covered by Section 10(a) or Section 10(b) against an indemnitee (a “**Covered Party**”) with respect to which the Covered Party intends to seek indemnification under this Agreement, the Covered Party shall give prompt written notice of the Claim to the indemnifying party, including a brief description of the amount and basis for the Claim, if known.  Upon receiving such notice, the indemnifying party shall be obligated to defend the Covered Party against the Claim, and shall be entitled to assume control of the defense and settlement of the Claim.  The Covered Party may participate in the defense and settlement of the Claim at its own expense, using its own counsel, but without any right of control.  The indemnifying party shall keep the Covered Party reasonably apprised as to the status of the Claim.  Neither the indemnifying party nor any Covered Party shall be liable for any settlement of a Claim made without its consent.  Notwithstanding the foregoing, the Covered Party shall retain responsibility for all aspects of the Claim that are not subject to indemnification by the indemnifying party hereunder.  

11. **Limitation of Liability**. 

EXCEPT AS PROHIBITED BY LAW, IN NO EVENT WILL DEELI BE LIABLE UNDER OR IN CONNECTION WITH THESE TERMS UNDER ANY LEGAL OR EQUITABLE THEORY, INCLUDING BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR OTHERWISE, FOR ANY: (A) CONSEQUENTIAL, INCIDENTAL, INDIRECT, EXEMPLARY, SPECIAL, ENHANCED, OR PUNITIVE DAMAGES; (B) INCREASED COSTS, DIMINUTION IN VALUE OR LOST BUSINESS, PRODUCTION, REVENUES, OR PROFITS; (C) LOSS OF GOODWILL OR REPUTATION; (D) USE, INABILITY TO USE, LOSS, INTERRUPTION, DELAY OR RECOVERY OF ANY DATA, OR BREACH OF DATA OR SYSTEM SECURITY; OR (E) COST OF REPLACEMENT GOODS OR SERVICES, IN EACH CASE REGARDLESS OF WHETHER DEELI WAS ADVISED OF THE POSSIBILITY OF SUCH LOSSES OR DAMAGES OR SUCH LOSSES OR DAMAGES WERE OTHERWISE FORESEEABLE. EXCEPT AS PROHIBITED BY LAW, IN NO EVENT WILL DEELI’S AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THESE TERMS UNDER ANY LEGAL OR EQUITABLE THEORY, INCLUDING BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR OTHERWISE EXCEED THE TOTAL AMOUNTS PAID TO DEELI UNDER THESE TERMS IN THE TWELVE (12) MONTH PERIOD PRECEDING THE EVENT GIVING RISE TO THE CLAIM. 

1.  **Governing Law; Dispute Resolution**.

These Terms shall be governed by the laws of California without giving effect to any choice or conflict of law provision or rule that would require or permit the application of the laws of any jurisdiction other than those of the State of California.  The parties shall try in good faith to resolve any dispute or claim related to or arising out of these Terms, or the interpretation, making, performance, breach or termination thereof, amicably by themselves.  If the dispute or claim cannot be resolved by the parties themselves, then it shall be adjudicated exclusively by the state and federal courts located in San Francisco County, California.  Notwithstanding the foregoing, the parties may apply to any court of competent jurisdiction for temporary or permanent injunctive relief without breach of this Section 12. 

1.  **Miscellaneous**.

    1. Modifications. You acknowledge and agree that we have the right, in our sole discretion, to modify these Terms from time to time, and that such modified terms become effective on posting or providing them to you.  You will be notified of modifications by direct email or through notifications through the Services. You are responsible for reviewing and becoming familiar with any modifications. Your continued use of the Services after the effective date of the modifications will be deemed acceptance of the modified terms.

    2. Export Regulation. The Services utilize software and technology that may be subject to U.S. export control laws, including the U.S. Export Administration Act and its associated regulations. You shall not, directly or indirectly, export, re-export, or release the Services or the software or technology included in the Services to, or make the Services or the software or technology included in the Services accessible from, any jurisdiction or country to which export, re-export, or release is prohibited by law, regulation, or rule. You shall comply with all applicable federal laws, regulations, and rules, and complete all required undertakings (including obtaining any necessary export license or other governmental approval), prior to exporting, re-exporting, releasing, or otherwise making the Services or the software or technology included in the Services available outside the U.S.

    3. Entire Agreement. These Terms, together with any amendments and any additional agreements you may enter into with Deeli in connection with the Services, shall constitute the entire agreement between you and Deeli concerning the Services, and supersedes all prior and contemporaneous understandings, agreements, representations, and warranties, both written and oral, with respect to such subject matter.  In the event of any inconsistency between the body of these Terms and any ordering documentation, the body of these Terms controls, unless the parties expressly indicate in such order an intent to deviate from the terms of these Terms.

    4. Notices. Any notices to us must be sent to <support@deeli.ai> or our mailing address available at 2 F., No. 453, Fuxing N. Rd., Songshan Dist., Taipei City 105003, Taiwan, and must be delivered either in person, by email, certified or registered mail, return receipt requested and postage prepaid, or by recognized overnight courier service, and are deemed given upon receipt by us. Notwithstanding the foregoing, you hereby consent to receiving electronic communications from us. These electronic communications may include notices about applicable fees and charges, transactional information, and other information concerning or related to the Services. You agree that any notices, agreements, disclosures, or other communications that we send to you electronically will satisfy any legal communication requirements, including that such communications be in writing. 

    5. Severability. The invalidity, illegality, or unenforceability of any provision herein does not affect any other provision herein or the validity, legality, or enforceability of such provision in any other jurisdiction.

    6. No Waiver. No waiver of any term of these Terms shall be deemed a further or continuing waiver of such term or any other term, and Deeli’s failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision. Any failure to act by us with respect to a breach of these Terms by you or others does not constitute a waiver and will not limit our rights with respect to such breach or any subsequent breaches.

    7. Assignment. These Terms, and any rights and licenses granted hereunder, are personal to you and may not be assigned or transferred for any reason whatsoever without our prior written consent and any action or conduct in violation of the foregoing will be void and without effect. We expressly reserve the right to assign these Terms and to delegate any of its obligations hereunder.

    8. Contact Us.  Please contact us at <support@deeli.ai> with any inquires regarding these Terms. 

                        © Deeli AI, Inc. 2025 – All Rights Reserved
`;

const TermsOfService = () => {
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down("sm"));
  const [termsContent, setTermsContent] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Load the terms of service markdown file
    const loadTerms = async () => {
      try {
        const response = await fetch("/terms-of-service.md");
        if (!response.ok) {
          throw new Error(`HTTP error! status: ${response.status}`);
        }
        const content = await response.text();
        setTermsContent(content);
      } catch (error) {
        console.error("Error loading terms of service:", error);
        // Fallback content if markdown file is not found
        setTermsContent(`# Terms of Service

**Last Updated:** ${new Date().toLocaleDateString()}

Welcome to Deeli AI. These Terms of Service govern your use of our website and services.

## 1. Acceptance of Terms

By accessing or using our Service, you agree to be bound by these Terms.

## 2. Description of Service

Deeli AI provides AI-powered insights and analytics services designed to help businesses understand trends and make data-driven decisions.

## 3. Contact Information

If you have any questions about these Terms, please contact us at support@deeli.ai.

---

*Please note: This is fallback content. The full terms of service should be loaded from the markdown file.*`);
      } finally {
        setLoading(false);
      }
    };

    loadTerms();
  }, []);

  const handleBack = () => {
    window.history.back();
  };

  const markdownComponents = {
    h1: ({ children }) => (
      <Typography
        variant="h1"
        sx={{
          fontSize: isMobile ? "2rem" : "2.5rem",
          fontWeight: 700,
          color: "#132B24",
          marginBottom: "1.5rem",
          marginTop: "2rem",
          fontFamily: "Manrope",
        }}
      >
        {children}
      </Typography>
    ),
    h2: ({ children }) => (
      <Typography
        variant="h2"
        sx={{
          fontSize: isMobile ? "1.5rem" : "2rem",
          fontWeight: 600,
          color: "#132B24",
          marginBottom: "1rem",
          marginTop: "2rem",
          fontFamily: "Manrope",
        }}
      >
        {children}
      </Typography>
    ),
    h3: ({ children }) => (
      <Typography
        variant="h3"
        sx={{
          fontSize: isMobile ? "1.25rem" : "1.5rem",
          fontWeight: 600,
          color: "#132B24",
          marginBottom: "0.75rem",
          marginTop: "1.5rem",
          fontFamily: "Manrope",
        }}
      >
        {children}
      </Typography>
    ),
    p: ({ children }) => (
      <Typography
        variant="body1"
        sx={{
          fontSize: "1rem",
          lineHeight: 1.6,
          color: "#333333",
          marginBottom: "1rem",
          fontFamily: "Aileron",
        }}
      >
        {children}
      </Typography>
    ),
    ul: ({ children }) => (
      <Box
        component="ul"
        sx={{
          paddingLeft: "1.5rem",
          marginBottom: "1rem",
          "& li": {
            marginBottom: "0.5rem",
            color: "#333333",
            fontFamily: "Aileron",
          },
        }}
      >
        {children}
      </Box>
    ),
    ol: ({ children }) => (
      <Box
        component="ol"
        sx={{
          paddingLeft: "1.5rem",
          marginBottom: "1rem",
          "& li": {
            marginBottom: "0.5rem",
            color: "#333333",
            fontFamily: "Aileron",
          },
        }}
      >
        {children}
      </Box>
    ),
    strong: ({ children }) => (
      <Typography
        component="strong"
        sx={{
          fontWeight: 600,
          color: "#132B24",
        }}
      >
        {children}
      </Typography>
    ),
    em: ({ children }) => (
      <Typography
        component="em"
        sx={{
          fontStyle: "italic",
          color: "#555555",
        }}
      >
        {children}
      </Typography>
    ),
  };

  return (
    <Box sx={{ minHeight: "100vh", backgroundColor: "#FFFFFF" }}>
      <AppBar
        position="static"
        sx={{
          backgroundColor: "#FFFFFF",
          boxShadow: "0px 1px 3px rgba(0, 0, 0, 0.1)",
          color: "#132B24",
        }}
      >
        <Toolbar>
          <Button
            startIcon={<ArrowLeft size={20} />}
            onClick={handleBack}
            sx={{
              color: "#132B24",
              textTransform: "none",
              fontFamily: "Aileron",
              fontSize: "1rem",
            }}
          >
            Back
          </Button>
          <Box 
            sx={{ 
              flexGrow: 1,
              display: "flex",
              justifyContent: "center",
              alignItems: "center"
            }}
          >
            <img
              loading="lazy"
              src={Logo}
              alt="Logo"
              style={{
                height: 33.28,
                width: 105.42,
              }}
            />
          </Box>
          <Box sx={{ width: "80px" }} /> {/* Spacer for centering */}
        </Toolbar>
      </AppBar>

      <Container
        maxWidth="md"
        sx={{
          paddingTop: "2rem",
          paddingBottom: "3rem",
          paddingX: isMobile ? "1rem" : "2rem",
        }}
      >
        {loading ? (
          <Box
            sx={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              minHeight: "400px",
            }}
          >
            <CircularProgress sx={{ color: "#096B5F" }} />
          </Box>
        ) : (
          <Box
            sx={{
              backgroundColor: "#FFFFFF",
              borderRadius: "8px",
              padding: isMobile ? "1.5rem" : "2rem",
              boxShadow: "0px 2px 8px rgba(0, 0, 0, 0.1)",
            }}
          >
            <ReactMarkdown components={markdownComponents}>
              {TERMS_CONTENT}
            </ReactMarkdown>
          </Box>
        )}
      </Container>
    </Box>
  );
};

export default TermsOfService;